
import { CanonicalSchema, Table, Column } from '../types';

export const schemaToPostgresSQL = (schema: CanonicalSchema): string => {
  let sql = `-- Generated by SupaSQL\n\n`;

  schema.tables.forEach((table) => {
    sql += `CREATE TABLE "${table.name}" (\n`;
    const columnDefinitions = table.columns.map((col) => {
      let def = `  "${col.name}" ${col.type.toUpperCase()}`;
      if (col.isPrimaryKey) def += ` PRIMARY KEY`;
      if (!col.isNullable) def += ` NOT NULL`;
      if (col.isUnique) def += ` UNIQUE`;
      if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`;
      return def;
    });
    sql += columnDefinitions.join(',\n');
    sql += `\n);\n\n`;
  });

  schema.relationships.forEach((rel) => {
    sql += `ALTER TABLE "${rel.fromTable}" ADD CONSTRAINT "fk_${rel.fromTable}_${rel.fromColumn}" \n`;
    sql += `FOREIGN KEY ("${rel.fromColumn}") REFERENCES "${rel.toTable}" ("${rel.toColumn}");\n\n`;
  });

  return sql;
};

export const calculateMigrationDiff = (prev: CanonicalSchema, next: CanonicalSchema) => {
    // Basic diff logic for demonstration
    const steps: string[] = [];
    next.tables.forEach(table => {
        const prevTable = prev.tables.find(t => t.id === table.id);
        if (!prevTable) {
            steps.push(`CREATE TABLE "${table.name}" (...);`);
        } else {
            table.columns.forEach(col => {
                if (!prevTable.columns.find(pc => pc.id === col.id)) {
                    steps.push(`ALTER TABLE "${table.name}" ADD COLUMN "${col.name}" ${col.type.toUpperCase()};`);
                }
            });
        }
    });
    return steps;
}
